### ISSUE TITLE
random error on player leave

### ISSUE THREAD

**Issue by seema84** [crashdemons/AztecTabCompleter#6] opened 2018-11-26 20:53 UTC
i get sometimes this error if a player leave
error ->
https://pastebin.com/eVS9CTLC

"The method hasPermission is not supported for temporary players."

**Comment by crashdemons** [comment] 2018-11-28 06:20
This most likely occurs now when #1 occurs (player joins and immediately leaves).

I can probably solve the "temporary player" error by queueing the commands list until the join event (Task #7 now) but note that a player can leave at any time.  If they leave during packet send, this will still cause protocollib to print a [different] exception to the log as in #1

**Comment by crashdemons** [comment] 2018-11-28 21:00
Can you try this snapshot version?   [AztecTabCompleter-0.19.2-SNAPSHOT.jar](https://ci.meme.tips/job/AztecTabCompleter/18/artifact/target/AztecTabCompleter-0.19.2-SNAPSHOT.jar) (build 18)

**Comment by seema84** [comment] 2018-11-29 00:57
yes i can test it but its not so easy to reproduce
your output (4-5 messages) every player join and restart its too much

**Comment by crashdemons** [comment] 2018-11-29 02:12
I understand, but this is an early alpha for testing - the messages will be removed in release. If you require a alpha without the logging, I could rebuild one. (doing so presently)

**Comment by crashdemons** [comment] 2018-11-29 02:17
This build has reduced logging [https://ci.meme.tips/job/AztecTabCompleter/19/artifact/target/AztecTabCompleter-0.19.2-SNAPSHOT.jar](https://ci.meme.tips/job/AztecTabCompleter/19/artifact/target/AztecTabCompleter-0.19.2-SNAPSHOT.jar) (build 19)

[_I should note again while this may fix the "temporary player" message - Issue #1 can still occur if the player disconnects while the join event/retry is still running (protocolib prints an error not this plugin and not catchable)_]

**Comment by seema84** [comment] 2018-11-29 02:29
maybe you find a good solution to fix this problem in all cases

**Comment by crashdemons** [comment] 2018-11-29 02:37
I'm not sure what you're saying, but if you're saying I should just fix both problems:

The redesign in build 18 and 19 was to solve the problem you're having and reduce (but not eliminate) the possibility of Issue #1 occurring.

In Issue #1 I **cannot** prevent the "_cannot send packet to %s_" message from printing, because protocollib decides to print a message when it can't send a packet regardless of anything I can do.

- Even if I catch the exception, they still print the error first in their code.
- Even if you supply a valid Player to protocollib - the player can disconnect *while protocollib is sending*, which has nothing to do with my code.

Now, if the first problem still exists or you receive a different error, please do say so and I can get to work on fixing it, but some other things are outside of this plugin's control.

**Comment by seema84** [comment] 2018-11-29 02:45
okay thanks, i will test it

**Comment by crashdemons** [comment] 2019-01-05 01:44
Confirmed not fixed by personal log.

This is due to limitations in protocolib's temporary players - there is no way to uniquely identify people at the time of connection/commands.

An approach (and suggested by the protocollib documentation) would be to use getAddress and queue the packet for the player with the matching address to become available, but there's not a way to ensure this is the same player and this could lead to issues if players share an IP.

Blocked on Issue #8

**Comment by seema84** [comment] 2019-01-05 02:26
i think the best solution is, not to use protocollib (i found a other plugin that have no problems and works without protocollib)

**Comment by crashdemons** [comment] 2019-01-05 02:29
Which plugin?

I'd be interested in how it works without being able to capture the Commands packet.

Bukkit has command and tab-complete handling events, but they only capture events for the plugin you're making...  and this goes into actually modifying the command list live.

I guess they may be using an alternative to ProtocolLib, or relying on NMS code itself (which can break without warning)

**Comment by seema84** [comment] 2019-01-05 03:02
https://github.com/SpaicyGaming/AntiCommandSuggestions

**Comment by crashdemons** [comment] 2019-03-21 10:00
I haven't had this issue for a while with recent changes.

Regarding that plugin, it makes use of PlayerCommandSendEvent. The reason I was not using this was the plugin was originally made to support the early prereleases of spigot 1.13 and this feature was relatively new in builds despite [first being committed in july 2018](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/event/player/PlayerCommandSendEvent.java).

However, now that it is standard for quite a while, I've started work on a simplified branch that does not rely on protocollib: https://github.com/crashdemons/AztecTabCompleter/tree/bukkit-events-rework and builds available here: https://ci.meme.tips/job/AztecTabCompleter-BukkitEventRework/

this branch should maintain existing filtering behavior from 0.19.6

**Closed as completed** 2019-03-22 13:01 UTC
Labels: bug, potential-fix-submitted
